site_name: OndrejKascak
nick: OK
owner: Ondrej Kaščák
email: ondrej.kascak@gmail.com
profile_photo_path: /assets/img/ok_foto.jpg

navbar:
  tabs:
    tab1: O mne
    tab2: Webové publikovanie
    tab3: Galéria
    tab4: Blog



# Build settings
# slider_array: []
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  # - jekyll-maps
  # - jekyll-youtube

# maps:
#   google:
#     api_key: AIzaSyCpj6PQg2IPjpw0U1Q981y3JcxAePgPL0c

exclude:
  - Gemfile
  - Gemfile.lock
