title: OndrejKascak
email: ondrej.kascak@gmailc.om

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-maps
  # - flickraw
gems: [jekyll-youtube]

maps:
  google:
    api_key: AIzaSyCpj6PQg2IPjpw0U1Q981y3JcxAePgPL0c

exclude:
  - Gemfile
  - Gemfile.lock

# flickr:
#   screen_name: ondrejkascak
#   api_key: f5ca96b6b6946883b72b52f0b324d04e
#   api_secret: 749c32e5d33bf0da
